/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package busmanagementsystem;

import java.awt.Color;

/**
 *
 * @author Shibin B Shaji
 */
public class MainMenu extends javax.swing.JFrame {

    /**
     * Creates new form MainMenu
     */
    public MainMenu() {
        initComponents();
        TripPanel.setVisible(false);
        SchedulePanel.setVisible(false);
        RoutePanel.setVisible(false);
        BusPanel.setVisible(false);
        StaffPanel.setVisible(false);
        ForeseePanel.setVisible(false);
        ForeseePanel2.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        SidePanel = new javax.swing.JPanel();
        ScheduleButton = new javax.swing.JButton();
        TripButton = new javax.swing.JButton();
        RouteButton = new javax.swing.JButton();
        BusButton = new javax.swing.JButton();
        StaffButton = new javax.swing.JButton();
        ForeseeButton = new javax.swing.JButton();
        GoSafeLogo = new javax.swing.JLabel();
        TopPanel = new javax.swing.JPanel();
        CloseButton = new javax.swing.JButton();
        SelectOptionDisplay = new javax.swing.JPanel();
        ForeseePanel2 = new javax.swing.JPanel();
        Foreseetxt1 = new javax.swing.JLabel();
        about2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        ForeseePanel = new javax.swing.JPanel();
        Foreseetxt = new javax.swing.JLabel();
        about1 = new javax.swing.JLabel();
        FSource = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();
        Emp_id_staff1 = new javax.swing.JLabel();
        Emp_id_staff2 = new javax.swing.JLabel();
        FDestination = new javax.swing.JTextField();
        jSeparator5 = new javax.swing.JSeparator();
        Foresee = new javax.swing.JButton();
        StaffPanel = new javax.swing.JPanel();
        Staff = new javax.swing.JLabel();
        Emp_id_staff = new javax.swing.JLabel();
        EmpID = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        Search_Staff = new javax.swing.JButton();
        about = new javax.swing.JLabel();
        BusPanel = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        BusID = new javax.swing.JTextField();
        SearchBus = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        RoutePanel = new javax.swing.JPanel();
        RouteL = new javax.swing.JLabel();
        tripl = new javax.swing.JLabel();
        Tripid = new javax.swing.JTextField();
        TripidSeperator = new javax.swing.JSeparator();
        SearchRoute = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        SchedulePanel = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        TripIDSchedule = new javax.swing.JTextField();
        SearchTrip = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel11 = new javax.swing.JLabel();
        TripPanel = new javax.swing.JPanel();
        Schedule = new javax.swing.JLabel();
        Source = new javax.swing.JTextField();
        Destination = new javax.swing.JTextField();
        EnterSource = new javax.swing.JLabel();
        EnterDestination = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        SourceSeperator = new javax.swing.JSeparator();
        DestinationSeperator = new javax.swing.JSeparator();
        jLabel12 = new javax.swing.JLabel();
        SelectMenuTxt = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1366, 768));
        setUndecorated(true);
        getContentPane().setLayout(null);

        SidePanel.setBackground(new java.awt.Color(255, 102, 0));

        ScheduleButton.setBackground(new java.awt.Color(255, 102, 0));
        ScheduleButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ScheduleButton.setForeground(new java.awt.Color(82, 84, 83));
        ScheduleButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Pictures\\schedule.png")); // NOI18N
        ScheduleButton.setText("       Schedule");
        ScheduleButton.setBorder(null);
        ScheduleButton.setBorderPainted(false);
        ScheduleButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ScheduleButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        ScheduleButton.setFocusPainted(false);
        ScheduleButton.setMaximumSize(new java.awt.Dimension(100, 25));
        ScheduleButton.setMinimumSize(new java.awt.Dimension(100, 25));
        ScheduleButton.setPreferredSize(new java.awt.Dimension(100, 25));
        ScheduleButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ScheduleButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ScheduleButtonMouseExited(evt);
            }
        });
        ScheduleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ScheduleButtonActionPerformed(evt);
            }
        });

        TripButton.setBackground(new java.awt.Color(255, 102, 0));
        TripButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        TripButton.setForeground(new java.awt.Color(82, 84, 83));
        TripButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Pictures\\trip bag.png")); // NOI18N
        TripButton.setText("             Trip     ");
        TripButton.setBorderPainted(false);
        TripButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        TripButton.setFocusPainted(false);
        TripButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        TripButton.setIconTextGap(6);
        TripButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                TripButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                TripButtonMouseExited(evt);
            }
        });
        TripButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TripButtonActionPerformed(evt);
            }
        });

        RouteButton.setBackground(new java.awt.Color(255, 102, 0));
        RouteButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        RouteButton.setForeground(new java.awt.Color(82, 84, 83));
        RouteButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Pictures\\route copy.png")); // NOI18N
        RouteButton.setText("             Route     ");
        RouteButton.setBorderPainted(false);
        RouteButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        RouteButton.setFocusPainted(false);
        RouteButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        RouteButton.setIconTextGap(6);
        RouteButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                RouteButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                RouteButtonMouseExited(evt);
            }
        });
        RouteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RouteButtonActionPerformed(evt);
            }
        });

        BusButton.setBackground(new java.awt.Color(255, 102, 0));
        BusButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        BusButton.setForeground(new java.awt.Color(82, 84, 83));
        BusButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Pictures\\bus.png")); // NOI18N
        BusButton.setText("             Bus     ");
        BusButton.setBorderPainted(false);
        BusButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        BusButton.setFocusPainted(false);
        BusButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        BusButton.setIconTextGap(6);
        BusButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                BusButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                BusButtonMouseExited(evt);
            }
        });
        BusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusButtonActionPerformed(evt);
            }
        });

        StaffButton.setBackground(new java.awt.Color(255, 102, 0));
        StaffButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        StaffButton.setForeground(new java.awt.Color(82, 84, 83));
        StaffButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Pictures\\staffs.png")); // NOI18N
        StaffButton.setText("             Staff     ");
        StaffButton.setBorderPainted(false);
        StaffButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        StaffButton.setFocusPainted(false);
        StaffButton.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        StaffButton.setIconTextGap(6);
        StaffButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                StaffButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                StaffButtonMouseExited(evt);
            }
        });
        StaffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StaffButtonActionPerformed(evt);
            }
        });

        ForeseeButton.setBackground(new java.awt.Color(255, 102, 0));
        ForeseeButton.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        ForeseeButton.setForeground(new java.awt.Color(82, 84, 83));
        ForeseeButton.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Pictures\\eyegosafe.png")); // NOI18N
        ForeseeButton.setText("       Foresee");
        ForeseeButton.setBorder(null);
        ForeseeButton.setBorderPainted(false);
        ForeseeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ForeseeButton.setDebugGraphicsOptions(javax.swing.DebugGraphics.BUFFERED_OPTION);
        ForeseeButton.setFocusPainted(false);
        ForeseeButton.setMaximumSize(new java.awt.Dimension(100, 25));
        ForeseeButton.setMinimumSize(new java.awt.Dimension(100, 25));
        ForeseeButton.setPreferredSize(new java.awt.Dimension(100, 25));
        ForeseeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ForeseeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ForeseeButtonMouseExited(evt);
            }
        });
        ForeseeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForeseeButtonActionPerformed(evt);
            }
        });

        GoSafeLogo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Documents\\menuogogosafe.png")); // NOI18N

        javax.swing.GroupLayout SidePanelLayout = new javax.swing.GroupLayout(SidePanel);
        SidePanel.setLayout(SidePanelLayout);
        SidePanelLayout.setHorizontalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addGroup(SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(RouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(StaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(ForeseeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GoSafeLogo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        SidePanelLayout.setVerticalGroup(
            SidePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(SidePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(GoSafeLogo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addComponent(ForeseeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ScheduleButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(TripButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RouteButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(BusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(StaffButton, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        getContentPane().add(SidePanel);
        SidePanel.setBounds(0, 0, 350, 770);

        TopPanel.setBackground(new java.awt.Color(82, 84, 83));

        CloseButton.setBackground(new java.awt.Color(82, 84, 83));
        CloseButton.setFont(new java.awt.Font("Arial Black", 0, 13)); // NOI18N
        CloseButton.setForeground(new java.awt.Color(255, 255, 255));
        CloseButton.setText("X");
        CloseButton.setBorderPainted(false);
        CloseButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CloseButton.setFocusable(false);
        CloseButton.setPreferredSize(new java.awt.Dimension(40, 40));
        CloseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CloseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout TopPanelLayout = new javax.swing.GroupLayout(TopPanel);
        TopPanel.setLayout(TopPanelLayout);
        TopPanelLayout.setHorizontalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, TopPanelLayout.createSequentialGroup()
                .addGap(0, 972, Short.MAX_VALUE)
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        TopPanelLayout.setVerticalGroup(
            TopPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(TopPanelLayout.createSequentialGroup()
                .addComponent(CloseButton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(90, Short.MAX_VALUE))
        );

        getContentPane().add(TopPanel);
        TopPanel.setBounds(350, 0, 1020, 130);

        SelectOptionDisplay.setBackground(new java.awt.Color(82, 84, 83));
        SelectOptionDisplay.setLayout(null);

        ForeseePanel2.setBackground(new java.awt.Color(84, 82, 83));

        Foreseetxt1.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Foreseetxt1.setForeground(new java.awt.Color(255, 255, 255));
        Foreseetxt1.setText("Foresee");

        about2.setForeground(new java.awt.Color(255, 255, 255));
        about2.setText("Be alerted on these areas while driving.");

        jTable1.setBackground(new java.awt.Color(84, 82, 83));
        jTable1.setForeground(new java.awt.Color(255, 255, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null},
                {null, null}
            },
            new String [] {
                "Title 1", "Title 2"
            }
        ));
        jTable1.setRowHeight(20);
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout ForeseePanel2Layout = new javax.swing.GroupLayout(ForeseePanel2);
        ForeseePanel2.setLayout(ForeseePanel2Layout);
        ForeseePanel2Layout.setHorizontalGroup(
            ForeseePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForeseePanel2Layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addGroup(ForeseePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(ForeseePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(about2, javax.swing.GroupLayout.PREFERRED_SIZE, 701, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(Foreseetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(214, Short.MAX_VALUE))
        );
        ForeseePanel2Layout.setVerticalGroup(
            ForeseePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ForeseePanel2Layout.createSequentialGroup()
                .addGap(58, 58, 58)
                .addComponent(Foreseetxt1, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(about2, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
        );

        SelectOptionDisplay.add(ForeseePanel2);
        ForeseePanel2.setBounds(0, 0, 1020, 640);

        ForeseePanel.setBackground(new java.awt.Color(82, 84, 83));
        ForeseePanel.setLayout(null);

        Foreseetxt.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Foreseetxt.setForeground(new java.awt.Color(255, 255, 255));
        Foreseetxt.setText("Foresee");
        ForeseePanel.add(Foreseetxt);
        Foreseetxt.setBounds(100, 60, 196, 61);

        about1.setForeground(new java.awt.Color(255, 255, 255));
        about1.setText("Enter the Source and Destination to get look ahead into the path.");
        ForeseePanel.add(about1);
        about1.setBounds(100, 130, 701, 59);

        FSource.setBackground(new java.awt.Color(82, 84, 83));
        FSource.setForeground(new java.awt.Color(255, 255, 255));
        FSource.setToolTipText("Enter Trip ID");
        FSource.setBorder(null);
        FSource.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FSourceActionPerformed(evt);
            }
        });
        ForeseePanel.add(FSource);
        FSource.setBounds(220, 260, 280, 39);

        jSeparator4.setBackground(new java.awt.Color(255, 102, 0));
        jSeparator4.setForeground(new java.awt.Color(255, 102, 0));
        ForeseePanel.add(jSeparator4);
        jSeparator4.setBounds(610, 300, 280, 10);

        Emp_id_staff1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Emp_id_staff1.setForeground(new java.awt.Color(255, 255, 255));
        Emp_id_staff1.setText("From Source:");
        ForeseePanel.add(Emp_id_staff1);
        Emp_id_staff1.setBounds(110, 270, 100, 28);

        Emp_id_staff2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Emp_id_staff2.setForeground(new java.awt.Color(255, 255, 255));
        Emp_id_staff2.setText("to Destination:");
        ForeseePanel.add(Emp_id_staff2);
        Emp_id_staff2.setBounds(510, 270, 100, 28);

        FDestination.setBackground(new java.awt.Color(82, 84, 83));
        FDestination.setForeground(new java.awt.Color(255, 255, 255));
        FDestination.setToolTipText("Enter Trip ID");
        FDestination.setBorder(null);
        FDestination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FDestinationActionPerformed(evt);
            }
        });
        ForeseePanel.add(FDestination);
        FDestination.setBounds(610, 260, 280, 39);

        jSeparator5.setBackground(new java.awt.Color(255, 102, 0));
        jSeparator5.setForeground(new java.awt.Color(255, 102, 0));
        ForeseePanel.add(jSeparator5);
        jSeparator5.setBounds(220, 300, 280, 10);

        Foresee.setBackground(new java.awt.Color(255, 102, 0));
        Foresee.setText("Foresee");
        Foresee.setBorder(null);
        Foresee.setBorderPainted(false);
        Foresee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Foresee.setFocusPainted(false);
        Foresee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ForeseeActionPerformed(evt);
            }
        });
        ForeseePanel.add(Foresee);
        Foresee.setBounds(500, 350, 111, 42);

        SelectOptionDisplay.add(ForeseePanel);
        ForeseePanel.setBounds(0, 0, 1020, 640);

        StaffPanel.setBackground(new java.awt.Color(82, 84, 83));
        StaffPanel.setLayout(null);

        Staff.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Staff.setForeground(new java.awt.Color(255, 255, 255));
        Staff.setText("Staff");
        StaffPanel.add(Staff);
        Staff.setBounds(100, 60, 196, 61);

        Emp_id_staff.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        Emp_id_staff.setForeground(new java.awt.Color(255, 255, 255));
        Emp_id_staff.setText("Employee ID:");
        StaffPanel.add(Emp_id_staff);
        Emp_id_staff.setBounds(100, 270, 100, 28);

        EmpID.setBackground(new java.awt.Color(82, 84, 83));
        EmpID.setForeground(new java.awt.Color(255, 255, 255));
        EmpID.setToolTipText("Enter Trip ID");
        EmpID.setBorder(null);
        EmpID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmpIDActionPerformed(evt);
            }
        });
        StaffPanel.add(EmpID);
        EmpID.setBounds(190, 260, 280, 39);

        jSeparator3.setBackground(new java.awt.Color(255, 102, 0));
        jSeparator3.setForeground(new java.awt.Color(255, 102, 0));
        StaffPanel.add(jSeparator3);
        jSeparator3.setBounds(190, 300, 280, 10);

        Search_Staff.setBackground(new java.awt.Color(255, 102, 0));
        Search_Staff.setText("Search Staff");
        Search_Staff.setBorder(null);
        Search_Staff.setBorderPainted(false);
        Search_Staff.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        Search_Staff.setFocusPainted(false);
        Search_Staff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Search_StaffActionPerformed(evt);
            }
        });
        StaffPanel.add(Search_Staff);
        Search_Staff.setBounds(260, 320, 111, 42);

        about.setForeground(new java.awt.Color(255, 255, 255));
        about.setText("Enter Employee ID to get Employee details.");
        StaffPanel.add(about);
        about.setBounds(100, 130, 701, 59);

        SelectOptionDisplay.add(StaffPanel);
        StaffPanel.setBounds(0, 0, 1020, 650);

        BusPanel.setBackground(new java.awt.Color(82, 84, 83));
        BusPanel.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bus");
        BusPanel.add(jLabel4);
        jLabel4.setBounds(100, 90, 196, 61);

        jLabel5.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Bus ID:");
        BusPanel.add(jLabel5);
        jLabel5.setBounds(100, 260, 66, 28);

        BusID.setBackground(new java.awt.Color(82, 84, 83));
        BusID.setForeground(new java.awt.Color(255, 255, 255));
        BusID.setToolTipText("Enter Trip ID");
        BusID.setBorder(null);
        BusID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BusIDActionPerformed(evt);
            }
        });
        BusPanel.add(BusID);
        BusID.setBounds(150, 250, 260, 39);

        SearchBus.setBackground(new java.awt.Color(255, 102, 0));
        SearchBus.setText("Search Bus");
        SearchBus.setBorder(null);
        SearchBus.setBorderPainted(false);
        SearchBus.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchBus.setFocusPainted(false);
        SearchBus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchBusActionPerformed(evt);
            }
        });
        BusPanel.add(SearchBus);
        SearchBus.setBounds(220, 320, 111, 42);

        jSeparator2.setBackground(new java.awt.Color(255, 102, 0));
        jSeparator2.setForeground(new java.awt.Color(255, 102, 0));
        BusPanel.add(jSeparator2);
        jSeparator2.setBounds(150, 290, 260, 10);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("Enter Bus ID to get details of the bus.");
        BusPanel.add(jLabel9);
        jLabel9.setBounds(100, 160, 500, 50);

        SelectOptionDisplay.add(BusPanel);
        BusPanel.setBounds(0, 0, 1020, 660);

        RoutePanel.setBackground(new java.awt.Color(82, 84, 83));
        RoutePanel.setLayout(null);

        RouteL.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        RouteL.setForeground(new java.awt.Color(255, 255, 255));
        RouteL.setText("Route");
        RoutePanel.add(RouteL);
        RouteL.setBounds(100, 80, 196, 61);

        tripl.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tripl.setForeground(new java.awt.Color(255, 255, 255));
        tripl.setText("Trip ID:");
        RoutePanel.add(tripl);
        tripl.setBounds(100, 260, 66, 28);

        Tripid.setBackground(new java.awt.Color(82, 84, 83));
        Tripid.setForeground(new java.awt.Color(255, 255, 255));
        Tripid.setToolTipText("Enter Trip ID");
        Tripid.setBorder(null);
        Tripid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TripidActionPerformed(evt);
            }
        });
        RoutePanel.add(Tripid);
        Tripid.setBounds(150, 260, 260, 39);

        TripidSeperator.setBackground(new java.awt.Color(255, 102, 0));
        TripidSeperator.setForeground(new java.awt.Color(255, 102, 0));
        RoutePanel.add(TripidSeperator);
        TripidSeperator.setBounds(150, 300, 260, 10);

        SearchRoute.setBackground(new java.awt.Color(255, 102, 0));
        SearchRoute.setText("Search Route");
        SearchRoute.setBorder(null);
        SearchRoute.setBorderPainted(false);
        SearchRoute.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchRoute.setFocusPainted(false);
        RoutePanel.add(SearchRoute);
        SearchRoute.setBounds(220, 330, 111, 42);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Enter Trip ID for Journey details like Distance, Journey hours, Source and Destination.");
        RoutePanel.add(jLabel10);
        jLabel10.setBounds(100, 140, 520, 50);

        SelectOptionDisplay.add(RoutePanel);
        RoutePanel.setBounds(0, -10, 1020, 650);

        SchedulePanel.setBackground(new java.awt.Color(82, 84, 83));
        SchedulePanel.setLayout(null);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Schedule");
        SchedulePanel.add(jLabel2);
        jLabel2.setBounds(90, 80, 196, 61);

        jLabel3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Trip ID:");
        SchedulePanel.add(jLabel3);
        jLabel3.setBounds(90, 250, 66, 28);

        TripIDSchedule.setBackground(new java.awt.Color(82, 84, 83));
        TripIDSchedule.setForeground(new java.awt.Color(255, 255, 255));
        TripIDSchedule.setToolTipText("Enter Trip ID");
        TripIDSchedule.setBorder(null);
        TripIDSchedule.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TripIDScheduleActionPerformed(evt);
            }
        });
        SchedulePanel.add(TripIDSchedule);
        TripIDSchedule.setBounds(140, 240, 260, 39);

        SearchTrip.setBackground(new java.awt.Color(255, 102, 0));
        SearchTrip.setText("Search Trip");
        SearchTrip.setBorder(null);
        SearchTrip.setBorderPainted(false);
        SearchTrip.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        SearchTrip.setFocusPainted(false);
        SchedulePanel.add(SearchTrip);
        SearchTrip.setBounds(210, 300, 111, 42);

        jSeparator1.setBackground(new java.awt.Color(255, 102, 0));
        jSeparator1.setForeground(new java.awt.Color(255, 102, 0));
        SchedulePanel.add(jSeparator1);
        jSeparator1.setBounds(140, 280, 260, 10);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Enter Trip ID to get bus timings.");
        SchedulePanel.add(jLabel11);
        jLabel11.setBounds(90, 150, 450, 40);

        SelectOptionDisplay.add(SchedulePanel);
        SchedulePanel.setBounds(0, 0, 1020, 640);

        TripPanel.setBackground(new java.awt.Color(82, 84, 83));
        TripPanel.setLayout(null);

        Schedule.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        Schedule.setForeground(new java.awt.Color(255, 255, 255));
        Schedule.setText("Trip");
        TripPanel.add(Schedule);
        Schedule.setBounds(80, 60, 68, 43);

        Source.setBackground(new java.awt.Color(82, 84, 83));
        Source.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Source.setForeground(new java.awt.Color(255, 255, 255));
        Source.setBorder(null);
        TripPanel.add(Source);
        Source.setBounds(238, 217, 366, 36);

        Destination.setBackground(new java.awt.Color(82, 84, 83));
        Destination.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        Destination.setForeground(new java.awt.Color(255, 255, 255));
        Destination.setBorder(null);
        Destination.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DestinationActionPerformed(evt);
            }
        });
        TripPanel.add(Destination);
        Destination.setBounds(238, 291, 366, 35);

        EnterSource.setBackground(new java.awt.Color(255, 255, 255));
        EnterSource.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EnterSource.setForeground(new java.awt.Color(255, 255, 255));
        EnterSource.setText("Enter Source:");
        TripPanel.add(EnterSource);
        EnterSource.setBounds(85, 217, 106, 22);

        EnterDestination.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        EnterDestination.setForeground(new java.awt.Color(255, 255, 255));
        EnterDestination.setText("Enter Destination:");
        TripPanel.add(EnterDestination);
        EnterDestination.setBounds(85, 296, 141, 22);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("Search");
        jButton1.setBorderPainted(false);
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        TripPanel.add(jButton1);
        jButton1.setBounds(357, 344, 114, 41);

        SourceSeperator.setBackground(new java.awt.Color(255, 102, 0));
        SourceSeperator.setForeground(new java.awt.Color(255, 102, 0));
        TripPanel.add(SourceSeperator);
        SourceSeperator.setBounds(238, 260, 366, 10);

        DestinationSeperator.setBackground(new java.awt.Color(255, 102, 0));
        DestinationSeperator.setForeground(new java.awt.Color(255, 102, 0));
        TripPanel.add(DestinationSeperator);
        DestinationSeperator.setBounds(238, 333, 366, 10);

        jLabel12.setBackground(new java.awt.Color(255, 255, 255));
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Enter Source and Destination to get Trip details.");
        TripPanel.add(jLabel12);
        jLabel12.setBounds(90, 120, 520, 40);

        SelectOptionDisplay.add(TripPanel);
        TripPanel.setBounds(0, 0, 1020, 640);

        SelectMenuTxt.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        SelectMenuTxt.setForeground(new java.awt.Color(255, 255, 255));
        SelectMenuTxt.setText("Select Menu");
        SelectOptionDisplay.add(SelectMenuTxt);
        SelectMenuTxt.setBounds(380, 70, 250, 60);

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\Shibin B Shaji\\Documents\\GoSafe.jpg")); // NOI18N
        jLabel1.setText("jLabel1");
        SelectOptionDisplay.add(jLabel1);
        jLabel1.setBounds(281, 206, 450, 250);

        getContentPane().add(SelectOptionDisplay);
        SelectOptionDisplay.setBounds(350, 130, 1020, 640);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void CloseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CloseButtonActionPerformed
        // TODO add your handling code here:
        CloseFrame();
    }//GEN-LAST:event_CloseButtonActionPerformed

    private void TripButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TripButtonActionPerformed
       TripPanel.setVisible(true);
      SchedulePanel.setVisible(false);
        RoutePanel.setVisible(false);
    BusPanel.setVisible(false);
StaffPanel.setVisible(false);
ForeseePanel.setVisible(false);
ForeseePanel2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_TripButtonActionPerformed

    private void ScheduleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ScheduleButtonActionPerformed
        SchedulePanel.setVisible(true);
        TripPanel.setVisible(false);
        RoutePanel.setVisible(false);
        BusPanel.setVisible(false);
        StaffPanel.setVisible(false);
        ForeseePanel.setVisible(false);
ForeseePanel2.setVisible(false);////void mouseEntered(MouseEvent e)
        //{
    //}  // TODO add your handling code here:
    }//GEN-LAST:event_ScheduleButtonActionPerformed

    private void TripButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TripButtonMouseEntered
        TripButton.setBackground(new Color(255,138,78));// TODO add your handling code here:
    }//GEN-LAST:event_TripButtonMouseEntered

    private void TripButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TripButtonMouseExited
       TripButton.setBackground(new Color(255,102,0)); // TODO add your handling code here:
    }//GEN-LAST:event_TripButtonMouseExited

    private void ScheduleButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleButtonMouseEntered
        ScheduleButton.setBackground(new Color(255,138,78));// TODO add your handling code here:
    }//GEN-LAST:event_ScheduleButtonMouseEntered

    private void ScheduleButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ScheduleButtonMouseExited
        ScheduleButton.setBackground(new Color(255,102,0));// TODO add your handling code here:
    }//GEN-LAST:event_ScheduleButtonMouseExited

    private void RouteButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RouteButtonMouseEntered
      RouteButton.setBackground(new Color(255,138,78));  // TODO add your handling code here:
    }//GEN-LAST:event_RouteButtonMouseEntered

    private void RouteButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_RouteButtonMouseExited
        RouteButton.setBackground(new Color(255,102,0));// TODO add your handling code here:
    }//GEN-LAST:event_RouteButtonMouseExited

    private void RouteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RouteButtonActionPerformed
    RoutePanel.setVisible(true);
    SchedulePanel.setVisible(false);
    TripPanel.setVisible(false);
    BusPanel.setVisible(false);
    StaffPanel.setVisible(false);
ForeseePanel.setVisible(false);
ForeseePanel2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_RouteButtonActionPerformed

    private void BusButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusButtonMouseEntered
        BusButton.setBackground(new Color(255,138,78));// TODO add your handling code here:
    }//GEN-LAST:event_BusButtonMouseEntered

    private void BusButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BusButtonMouseExited
        BusButton.setBackground(new Color(255,102,0));// TODO add your handling code here:
    }//GEN-LAST:event_BusButtonMouseExited

    private void BusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusButtonActionPerformed
        SchedulePanel.setVisible(false);
        TripPanel.setVisible(false);
        RoutePanel.setVisible(false);
        BusPanel.setVisible(true);
        StaffPanel.setVisible(false);
        ForeseePanel.setVisible(false);
ForeseePanel2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_BusButtonActionPerformed

    private void StaffButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffButtonMouseEntered
       StaffButton.setBackground(new Color(255,138,78)); // TODO add your handling code here:
    }//GEN-LAST:event_StaffButtonMouseEntered

    private void StaffButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_StaffButtonMouseExited
        StaffButton.setBackground(new Color(255,102,0));// TODO add your handling code here:
    }//GEN-LAST:event_StaffButtonMouseExited

    private void StaffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StaffButtonActionPerformed
        SchedulePanel.setVisible(false);
        TripPanel.setVisible(false);
        RoutePanel.setVisible(false);
        BusPanel.setVisible(false);
        StaffPanel.setVisible(true);
ForeseePanel.setVisible(false);
ForeseePanel2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_StaffButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void DestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DestinationActionPerformed

    private void TripIDScheduleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TripIDScheduleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TripIDScheduleActionPerformed

    private void TripidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TripidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TripidActionPerformed

    private void BusIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BusIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BusIDActionPerformed

    private void SearchBusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchBusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchBusActionPerformed

    private void EmpIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmpIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmpIDActionPerformed

    private void Search_StaffActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Search_StaffActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Search_StaffActionPerformed

    private void ForeseeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForeseeButtonMouseEntered
        ForeseeButton.setBackground(new Color(255,138,78));// TODO add your handling code here:
    }//GEN-LAST:event_ForeseeButtonMouseEntered

    private void ForeseeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ForeseeButtonMouseExited
        ForeseeButton.setBackground(new Color(255,102,0));// TODO add your handling code here:
    }//GEN-LAST:event_ForeseeButtonMouseExited

    private void ForeseeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForeseeButtonActionPerformed
        SchedulePanel.setVisible(false);
        TripPanel.setVisible(false);
        RoutePanel.setVisible(false);
        BusPanel.setVisible(false);
        StaffPanel.setVisible(false);
        ForeseePanel.setVisible(true); 
        ForeseePanel2.setVisible(false);// TODO add your handling code here:
    }//GEN-LAST:event_ForeseeButtonActionPerformed

    private void FSourceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FSourceActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FSourceActionPerformed

    private void FDestinationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FDestinationActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_FDestinationActionPerformed

    private void ForeseeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ForeseeActionPerformed
       SchedulePanel.setVisible(false);
        TripPanel.setVisible(false);
        RoutePanel.setVisible(false);
        BusPanel.setVisible(false);
        StaffPanel.setVisible(false);
        ForeseePanel.setVisible(false);
        ForeseePanel2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_ForeseeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Metro UI".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainMenu().setVisible(true);
            }
        });
    }
    public void CloseFrame()
    {
        super.dispose();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BusButton;
    private javax.swing.JTextField BusID;
    private javax.swing.JPanel BusPanel;
    private javax.swing.JButton CloseButton;
    private javax.swing.JTextField Destination;
    private javax.swing.JSeparator DestinationSeperator;
    private javax.swing.JTextField EmpID;
    private javax.swing.JLabel Emp_id_staff;
    private javax.swing.JLabel Emp_id_staff1;
    private javax.swing.JLabel Emp_id_staff2;
    private javax.swing.JLabel EnterDestination;
    private javax.swing.JLabel EnterSource;
    private javax.swing.JTextField FDestination;
    private javax.swing.JTextField FSource;
    private javax.swing.JButton Foresee;
    private javax.swing.JButton ForeseeButton;
    private javax.swing.JPanel ForeseePanel;
    private javax.swing.JPanel ForeseePanel2;
    private javax.swing.JLabel Foreseetxt;
    private javax.swing.JLabel Foreseetxt1;
    private javax.swing.JLabel GoSafeLogo;
    private javax.swing.JButton RouteButton;
    private javax.swing.JLabel RouteL;
    private javax.swing.JPanel RoutePanel;
    private javax.swing.JLabel Schedule;
    private javax.swing.JButton ScheduleButton;
    private javax.swing.JPanel SchedulePanel;
    private javax.swing.JButton SearchBus;
    private javax.swing.JButton SearchRoute;
    private javax.swing.JButton SearchTrip;
    private javax.swing.JButton Search_Staff;
    private javax.swing.JLabel SelectMenuTxt;
    private javax.swing.JPanel SelectOptionDisplay;
    private javax.swing.JPanel SidePanel;
    private javax.swing.JTextField Source;
    private javax.swing.JSeparator SourceSeperator;
    private javax.swing.JLabel Staff;
    private javax.swing.JButton StaffButton;
    private javax.swing.JPanel StaffPanel;
    private javax.swing.JPanel TopPanel;
    private javax.swing.JButton TripButton;
    private javax.swing.JTextField TripIDSchedule;
    private javax.swing.JPanel TripPanel;
    private javax.swing.JTextField Tripid;
    private javax.swing.JSeparator TripidSeperator;
    private javax.swing.JLabel about;
    private javax.swing.JLabel about1;
    private javax.swing.JLabel about2;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel tripl;
    // End of variables declaration//GEN-END:variables
}
